# Note: additional setup is required, see https://www.jenkins.io/redirect/continuous-delivery-of-plugins

name: cd
on:
  push:
    branches: master

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.verify-ci-status.outputs.result == 'success' && steps.interesting-categories.outputs.interesting == 'true' }}
    steps:
      - name: Check out
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          
      - name: Verify CI status
        uses: jenkins-infra/verify-ci-status-action@v1.2.0
        id: verify-ci-status
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output_result: true
          
      - name: Get Project Version from pom.xml
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion
        
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
#         if: steps.verify-ci-status.outputs.result == 'success'
        with:
          name: next
          tag: ${{ steps.getVersion.outputs.version }}
          version: ${{ steps.getVersion.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check interesting categories
        uses: jenkins-infra/interesting-category-action@v1.0.0
        id: interesting-categories
#         if: steps.verify-ci-status.outputs.result == 'success'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [validate]
#     if: needs.validate.outputs.should_release == 'true'
    steps:
    - name: Check out
      uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0
    - name: Set up JDK 8
      uses: actions/setup-java@v2.5.0
      with:
        distribution: temurin
        java-version: 8
    - name: Release
      uses: jenkins-infra/jenkins-maven-cd-action@v1.2.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
